name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: golang:1.22-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...
