// Package aptutil generates an apt.conf override that points apt at the
// host's package sources and dpkg status (read-only) while keeping every
// writable path apt needs (fetched indexes, locks, cache) inside a
// container-owned directory. The host filesystem is never written to.
package aptutil

import (
	"fmt"
	"os"
	"path/filepath"
)

// Config holds the paths needed to build the override.
type Config struct {
	SourcesList  string // host-mounted /etc/apt/sources.list (read-only)
	SourcesListD string // host-mounted /etc/apt/sources.list.d (read-only)
	DpkgStatus   string // host-mounted /var/lib/dpkg/status (read-only)
	ListsDir     string // container-owned, writable; e.g. /var/lib/update-detector/apt/lists
}

// Write renders the apt.conf override next to ListsDir and returns its path,
// suitable for the APT_CONFIG environment variable of any apt-get/apt-check
// invocation.
func Write(cfg Config) (string, error) {
	base := filepath.Dir(cfg.ListsDir)
	stateDir := filepath.Join(base, "state")
	cacheDir := filepath.Join(base, "cache")

	dirs := []string{
		cfg.ListsDir,
		filepath.Join(cfg.ListsDir, "partial"),
		stateDir,
		cacheDir,
		filepath.Join(cacheDir, "archives", "partial"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", fmt.Errorf("aptutil: creating %s: %w", dir, err)
		}
	}

	contents := fmt.Sprintf(`// generated by update-detector, do not edit
Dir::Etc::sourcelist "%s";
Dir::Etc::sourceparts "%s";
Dir::State "%s/";
Dir::State::Lists "%s";
Dir::State::status "%s";
Dir::Cache "%s/";
`, cfg.SourcesList, cfg.SourcesListD, stateDir, cfg.ListsDir, cfg.DpkgStatus, cacheDir)

	confPath := filepath.Join(base, "apt.conf")
	if err := os.WriteFile(confPath, []byte(contents), 0o644); err != nil {
		return "", fmt.Errorf("aptutil: writing %s: %w", confPath, err)
	}
	return confPath, nil
}
